### ISSUE TITLE
 PDFPig package PdfPig.Rendering.Skia  (0.1.9.3) is not AOT which causes runtime crash on iOS

### ISSUE THREAD

**Issue by petrsorfa** [UglyToad/PdfPig#942] opened 2024-11-22 02:18 UTC
Not sure if this is the correct place to log this issue, but PDFPig package PdfPig.Rendering.Skia  (0.1.9.3) is not AOT which causes runtime on startup crash on iOS.
For example when including it in a Godot dotnet build for .iOS

PDF package PdfPig.Rendering.Skia (0.1.9.1-alpha005) is built  with AOT and works with no mishaps on iOS

**Comment by BobLd** [comment] 2024-11-24 20:11
@petrsorfa thanks for opening an issue.

Because the problem is related to PdfPig.Rendering.Skia, can you open an issue in https://github.com/BobLd/PdfPig.Rendering.Skia ? I will help you here.

**Comment by BobLd** [comment] 2024-11-25 18:21
@petrsorfa also, can you provide details about the error you are getting on iOS? I'm using the package with AOT on both windows and Linux without issue

**Comment by BobLd** [comment] 2024-12-28 13:06
@petrsorfa I'm closing this issue, feel free to re-open one in the PdfPig.Rendering.Skia repos

**Closed by BobLd** 2024-12-28 13:06 UTC
