### ISSUE TITLE
Cropbox is wrong since update to 0.1.8

### ISSUE THREAD

**Issue by Hert79** [UglyToad/PdfPig#665] opened 2023-07-28 08:21 UTC
See attached example, top part of the text is not in the CropBox area of the page. This is a OCRd PDF where the original is kept as background image and the glyphs are set to invisible. 
[SmallCropbox.pdf](https://github.com/UglyToad/PdfPig/files/12192093/SmallCropbox.pdf)

This worked fine in release 0.1.7

**Comment by BobLd** [comment] 2023-07-28 18:26
Hi @Hert79 can you check this bug against the latest nightly build? It should have been fixed with https://github.com/UglyToad/PdfPig/pull/649

Let me know if not the case. I'll investigate further.

@EliotJones I think this regression is important enough to do a new release... on my side I can't release the updated version of tabula sharp. Let me know what you think

**Comment by Hert79** [comment] 2023-07-28 21:09
I'm on vacation for 2.5 weeks, will check it when I'm back.

**Comment by BobLd** [comment] 2023-07-29 11:51
@EliotJones also, as a side note (and I might be completely wrong), but I'm not sure having a different NuGet package for the Nightly release is a safe choice. I've never seen this approach in other packages (everyone seems to be using your previous approach where we had a single Nuget package, with release/pre-release flags). I doubt many people will test the nightly release in the other package, which deserve the purpose…We’d want as many people as possible doing testing before doing the actual package release. Let me know what you think or if I missed something

**Comment by Numpsy** [comment] 2023-08-03 09:42
> @EliotJones also, as a side note (and I might be completely wrong), but I'm not sure having a different NuGet package for the Nightly release is a safe choice. I've never seen this approach in other packages (everyone seems to be using your previous approach where we had a single Nuget package, with release/pre-release flags). I doubt many people will test the nightly release in the other package, which deserve the purpose…We’d want as many people as possible doing testing before doing the actual package release. Let me know what you think or if I missed something

fwiw, I've seen a bunch of other projects that put their nightly builds in a different nuget feed so as not to clutter up the nuget.org one but I don't recall any using a different package name for the nightlies

**Comment by EliotJones** [comment] 2023-08-05 15:32
Thanks for fixing this @BobLd, I will try and make a new release soon, pretty much swamped with work stuff currently. In the meantime we'll move nightlies back into the main package.

**Comment by Hert79** [comment] 2023-08-22 06:37
> Hi @Hert79 can you check this bug against the latest nightly build? It should have been fixed with #649
> 
> Let me know if not the case. I'll investigate further.
> 
> @EliotJones I think this regression is important enough to do a new release... on my side I can't release the updated version of tabula sharp. Let me know what you think

Hello, thanks for looking at it. I tried it again with build 0.1.9-alpha-20230806-4a480, but it seems the problem is still there.

**Closed** 2023-10-18 20:27 UTC
