### ISSUE TITLE
In certain PDFs, reported boundingbox rectangle does not seem to align with actual element positions correctly

### ISSUE THREAD

**Issue by rajasekarshanmugam** [UglyToad/PdfPig#406] opened 2022-01-06 06:53 UTC
We have a few PDFs that when processed with pdfpig library, enumerating the words and trying to print positions, we found that the word boundingbox returned by the library seems a bit off for some rows.

For e.g. VIsually when seen from adobe reader/chrome/edge, elements are positioned one below other. However when we try to get the bounding box via the library, subsequent rows positions are offset by large values (consistent for that row). 

Tried to debug the issue, checked if any page clipbox is setup, but none were there. Tried to check if any transforms were setup for word/letter, but could not find any functions/properties on word/letter to determine if any calculations are going wrong.

Also tried to use PDFbox, if it is reporting the positions correctly, it seems to render right too, adobe reader/edge/chrome also does the right thing.

Are there any specific debug methods that can be followed to identify the above issue? Certainly can clone and walk through the code, but unsure of the PDF primitives, so not clear where to start. If there are pointers, please let me know, meanwhile will try to walk through the library to check.

**Comment by rajasekarshanmugam** [comment] 2022-01-07 06:46
I can send a reproducible PDF. Tried stepping through source and comparing with positions as shown by PDFXEdit.exe, There seems to be some transform/offset missing.

**Comment by rajasekarshanmugam** [comment] 2022-01-10 09:51
tried debugging more along with the library source. Left position of a litter is determined by adjusting width by adding left positions and font sizes/boxes. it seems to be different between lines with different font sizes and hence seems to be offset. @EliotJones , is this a valid reason for the letter/word to not align correctly just like the previous row.  Is there an element offset/crop box for each letter/glyph too? Can you suggest any other easy way to debug this?

**Comment by EliotJones** [comment] 2022-01-10 12:02
Hi @rajasekarshanmugam sorry I don't have much time for PdfPig at the moment. It's hard to diagnose these issues without access to the source file.

I suspect the cause here is the size of the glyph/letter returned by `font.GetBoundingBox()`. This is then transformed by the matrix after line https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs#L280 but as far as I'm aware that code below that line should basically be right. However the actual size of the glyph depends on the type of font and it's possible there's a bug in there with respect to the width or height of the glyph.

Are you able to share the source file at all? I generally debug them by running the PDFBox code side by side and checking the values in https://github.com/apache/pdfbox/blob/trunk/pdfbox/src/main/java/org/apache/pdfbox/contentstream/PDFStreamEngine.java#L684

**Comment by rajasekarshanmugam** [comment] 2022-01-10 12:10
@EliotJones , i got approvals for sharing the PDF. Is there an email id I can send to (could not find it in your profile)? I have edited and removed a lot of content with only needed content to reproduce the issue. Thank you so much for your time. We tried by stepping through the content but could not make much headways.

**Comment by EliotJones** [comment] 2022-01-10 12:13
Are you able to share this redacted PDF publicly by attaching it to this thread (this will mean other contributors may be able to help with a fix)? If not you can email it to pdfpig@outlook.com.

**Comment by rajasekarshanmugam** [comment] 2022-01-10 12:24
@EliotJones , so far did not get that level of approval, but working on it. For now, I have sent the document over to the above email.

**Comment by rajasekarshanmugam** [comment] 2022-01-14 05:29
@EliotJones  thank you so much for looking into this.
Extending the above comment, offsets will be much higher in the next line, which could make it easier for debugging.

Sorry, github is not notifying me on this, would have reverted earlier.

**Comment by rajasekarshanmugam** [comment] 2022-01-14 12:28
@EliotJones , are those boxes added as annotations for debugging?

**Comment by EliotJones** [comment] 2022-01-14 14:13
@rajasekarshanmugam they're generated by this test https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig.Tests/Integration/VisualVerification/GenerateLetterBoundingBoxImages.cs#L119 where the page images are generated by importing the PDF into GIMP/Glimpse image editor at 72 pixels/inch.

**Comment by EliotJones** [comment] 2022-01-15 13:09
@rajasekarshanmugam so I managed to narrow down the issue here, it looks like the font used in this file is a combination of a TrueType and Adobe Standard 14 font. PdfPig was using the TrueType glyph metrics to calculate x-advance per character when it should be using the Standard14 metrics. This has been changed and should be in the NuGet released at midnight UTC tonight.

**Comment by rajasekarshanmugam** [comment] 2022-01-15 13:50
@EliotJones  will give it a try as soon as it's available. Again, thank you so much for your time.

**Comment by rajasekarshanmugam** [comment] 2022-01-16 05:33
@EliotJones, it works as expected, with the set of documents that looked similar to the test document. Can I close this issue as done?

**Comment by EliotJones** [comment] 2022-01-16 09:59
Thanks for letting me know, closing this now.

**Closed by EliotJones** 2022-01-16 09:59 UTC
Labels: bug, testing

**Comment by rajasekarshanmugam** [comment] 2022-01-17 06:25
@EliotJones , saw you have added a note on debug (https://github.com/UglyToad/PdfPig/wiki/Debugging-against-PDFBox) setup of pdfbox, its is very useful. 

Below is the gist we used to debug, hope it helps someone.
https://gist.github.com/rajasekarshanmugam/19c8165619a56e46201c9e78d4eee12a
