### ISSUE TITLE
The font does not contain a character

### ISSUE THREAD

**Issue by mareksip** [UglyToad/PdfPig#98] opened 2019-12-09 22:15 UTC
Hello, 

we are trying to write Czech letters (ISO 8859-2 or CP852) as Standard14Font does not seem to support these character we tried to implement using TrueTypeFont as following:

```
    var bytes = File.ReadAllBytes(@"C:/Personal Data/GIT/Fakturace/fakturace/fonts/times.ttf");
    var bytes = File.ReadAllBytes(@"C:/Users/flays/AppData/Local/Packages/046f5609-697c-42b1-a006-999ea2f3a60f_np2yhsb0vxx2g/LocalCache/arial.ttf");
    PdfDocumentBuilder.AddedFont font = builder.AddTrueTypeFont(bytes);
    IReadOnlyList<string> lst;
    IReadOnlyList<string> writeList;
    bool CanUseTrueTypeFont(IReadOnlyList<byte> fontFileBytes, out IReadOnlyList<string> reasons);

     builder.CanUseTrueTypeFont(bytes, out lst);
```

CanUseTrueTypeFont outputs list of 0 reasons with and when inspecting variable `font` the `Data` property value `/F0`. 

No characters are not written to the .pdf. When using Helvetica, writing works fine without Czech characters.

Could you please advice us how to write ISO 8859-2 characters?

**Comment by EliotJones** [comment] 2019-12-10 11:43
Hi, sorry you've hit one of the untested bits of the document creation implementation.

I've only tested with a few ASCII document texts previously so I don't think documents with non-ASCII characters are correctly handled presently (and even ASCII letters only work by luck!).

I definitely want the library to be able to support all Unicode characters however so I'll take a look and try and implement support for these characters.

**Comment by mareksip** [comment] 2019-12-10 12:14
> I definitely want the library to be able to support all Unicode characters however so I'll take a look and try and implement support for these characters.

Thanks for prompt reply. Supporting multiple encodings would support broader application of the library. 

I can try to implement the encoding support. Can you please point me to relevant parts of the library that should be extended?

**Comment by EliotJones** [comment] 2019-12-10 12:31
Thanks for your understanding and offer of help.

For document creation the TrueType font is currently written to the document here https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig/Writer/TrueTypeWritingFont.cs#L49 and the relevant section of the specification is 9.6.3 in this version https://www.adobe.com/content/dam/acom/en/devnet/pdf/PDF32000_2008.pdf.

Currently no `ToUnicode` cmap or `Encoding` is written for a TrueType font.

However I think the problem is also how the letters themselves are written into the content stream which is here https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs#L230

Rather than adding a show text operation which contains the actual text, e.g. `(h) Tj`, which will be invalid for non-ASCII characters it should instead add a hex code byte value which corresponds to the character code for the character in the corresponding TrueType font, for example `<AE> Tj`. This is detailed in the section 9.4.3 of the specification.

> With a simple font, each byte of the string shall be treated as a separate character code. The character code shall then be looked up in the font’s encoding to select the glyph, as described in 9.6.6, "Character Encoding". With  a  composite  font  (PDF  1.2),  multiple-byte  codes  may  be  used  to  select  glyphs.  In  this  instance,  one  or  more  consecutive  bytes  of  the  string  shall  be  treated  as  a  single  character  code.  The  code  lengths  and  the  mappings from codes to glyphs are defined in a data structure called a CMap,  described  in  9.7,  "Composite  Fonts".

So for multi-byte character codes we'd also need to add support for composite fonts.

**Comment by EliotJones** [comment] 2019-12-28 17:52
Hi Marek,

I've managed to start looking at this today, I was making some encouraging progress which allowed me to output Czech characters to the created document:

![image](https://user-images.githubusercontent.com/7862346/71547655-959cb900-299a-11ea-8170-eb156f1bad8b.png)

But unfortunately the created document becomes invalid because the TrueType file itself needs rewriting. I should be able to make a change that supports the necessary rewriting without having to develop an entire TrueType library (yet), but it's going to take longer than I thought. The linked commits have a lot more detail in the commit messages if you're interested.

**Comment by EliotJones** [comment] 2020-01-04 10:31
Hi Marek, I finally have a version I think is working for this use case, please try out the attached package and let me know if it works for what you were trying to do.

Thanks.
[PdfPig.0.0.11.98.zip](https://github.com/UglyToad/PdfPig/files/4021781/PdfPig.0.0.11.98.zip)

**Comment by mareksip** [comment] 2020-01-07 05:36
> 
> 
> Hi Marek, I finally have a version I think is working for this use case, please try out the attached package and let me know if it works for what you were trying to do.
> 
> Thanks.
> [PdfPig.0.0.11.98.zip](https://github.com/UglyToad/PdfPig/files/4021781/PdfPig.0.0.11.98.zip)

Hello Eliot, thank you for coming up with solution in such a prompt time. We will try your imlementation within upcoming days.

Thank you.

**Comment by EliotJones** [comment] 2020-03-15 21:38
Closing this as well because I believe it is included in #137. feel free to re-open if needed.

**Closed by EliotJones** 2020-03-15 21:38 UTC
Labels: bug, newfeature, testing

**Comment by matiqiu** [comment] 2022-07-09 00:50
Does the library already have the update?

**Comment by ggrote** [comment] 2024-05-15 08:07
I get the same error for the german characters ü. ä and ö using AddStandard14Font(Standard14Font.Helvetica)
