### ISSUE TITLE
Exception during PDF Read: Expected name as dictionary key, instead got: 1

### ISSUE THREAD

**Issue by bweberde** [UglyToad/PdfPig#511] opened 2022-11-14 00:09 UTC
Thank you for your Work!

As far as I can see the following construct in a pdf will trigger the exception at the NumericToken "1" right before "begincodespacerange"

```
/CIDInit /ProcSet findresource 
begin 12 dict 
begin begincmap 
CIDSystemInfo <<
/Registry (F2+0) /Ordering (F2) /Supplement 0
/CMapName /F2+0 def
/CMapType 2 def
**1** begincodespacerange <020D> <020D>  endcodespacerange
1 beginbfchar
<020D> <03A9>
endcmap CMapName currentdict /CMap defineresource pop end end
endbfchar
```

Unfortunatly I have no idea of the inner workings of a PDF... 

```
UglyToad.PdfPig.Core.PdfDocumentFormatException
  Message=Expected name as dictionary key, instead got: 1
  UglyToad.PdfPig.Tokenization.dll!UglyToad.PdfPig.Tokenization.DictionaryTokenizer.ConvertToDictionary(System.Collections.Generic.List<UglyToad.PdfPig.Tokens.IToken> tokens = Count = 30) Line 80
	at C:\Users\bw\ws\projects\nm\sfc\Extern\PdfPig\src\UglyToad.PdfPig.Tokenization\DictionaryTokenizer.cs(80)
UglyToad.PdfPig.Tokenization.dll!UglyToad.PdfPig.Tokenization.DictionaryTokenizer.TryTokenize(byte currentByte = 60, UglyToad.PdfPig.Core.IInputBytes inputBytes = {UglyToad.PdfPig.Core.ByteArrayInputBytes}, out UglyToad.PdfPig.Tokens.IToken token = null) Line 56
	at C:\Users\bw\ws\projects\nm\sfc\Extern\PdfPig\src\UglyToad.PdfPig.Tokenization\DictionaryTokenizer.cs(56)
UglyToad.PdfPig.Tokenization.dll!UglyToad.PdfPig.Tokenization.Scanner.CoreTokenScanner.MoveNext() Line 174
	at C:\Users\bw\ws\projects\nm\sfc\Extern\PdfPig\src\UglyToad.PdfPig.Tokenization\Scanner\CoreTokenScanner.cs(174)
UglyToad.PdfPig.dll!UglyToad.PdfPig.PdfFonts.Parser.CMapParser.Parse(UglyToad.PdfPig.Core.IInputBytes inputBytes = {UglyToad.PdfPig.Core.ByteArrayInputBytes}) Line 28
	at C:\Users\bw\ws\projects\nm\sfc\Extern\PdfPig\src\UglyToad.PdfPig\PdfFonts\Parser\CMapParser.cs(28)
UglyToad.PdfPig.dll!UglyToad.PdfPig.PdfFonts.Cmap.CMapCache.Parse(UglyToad.PdfPig.Core.IInputBytes bytes = {UglyToad.PdfPig.Core.ByteArrayInputBytes}) Line 45
	at C:\Users\bw\ws\projects\nm\sfc\Extern\PdfPig\src\UglyToad.PdfPig\PdfFonts\Cmap\CMapCache.cs(45)
UglyToad.PdfPig.dll!UglyToad.PdfPig.PdfFonts.Parser.Handlers.Type0FontHandler.Generate(UglyToad.PdfPig.Tokens.DictionaryToken dictionary = {UglyToad.PdfPig.Tokens.DictionaryToken}) Line 73
	at C:\Users\bw\ws\projects\nm\sfc\Extern\PdfPig\src\UglyToad.PdfPig\PdfFonts\Parser\Handlers\Type0FontHandler.cs(73)
UglyToad.PdfPig.dll!UglyToad.PdfPig.PdfFonts.FontFactory.Get(UglyToad.PdfPig.Tokens.DictionaryToken dictionary = {UglyToad.PdfPig.Tokens.DictionaryToken}) Line 44
	at C:\Users\bw\ws\projects\nm\sfc\Extern\PdfPig\src\UglyToad.PdfPig\PdfFonts\FontFactory.cs(44)
UglyToad.PdfPig.dll!UglyToad.PdfPig.Content.ResourceStore.LoadFontDictionary(UglyToad.PdfPig.Tokens.DictionaryToken fontDictionary = {UglyToad.PdfPig.Tokens.DictionaryToken}) Line 160
	at C:\Users\bw\ws\projects\nm\sfc\Extern\PdfPig\src\UglyToad.PdfPig\Content\ResourceStore.cs(160)
UglyToad.PdfPig.dll!UglyToad.PdfPig.Content.ResourceStore.LoadResourceDictionary(UglyToad.PdfPig.Tokens.DictionaryToken resourceDictionary = {UglyToad.PdfPig.Tokens.DictionaryToken}) Line 46
	at C:\Users\bw\ws\projects\nm\sfc\Extern\PdfPig\src\UglyToad.PdfPig\Content\ResourceStore.cs(46)
UglyToad.PdfPig.dll!UglyToad.PdfPig.Parser.PageFactory.Create(int number = 79, UglyToad.PdfPig.Tokens.DictionaryToken dictionary = {UglyToad.PdfPig.Tokens.DictionaryToken}, UglyToad.PdfPig.Content.PageTreeMembers pageTreeMembers = {UglyToad.PdfPig.Content.PageTreeMembers}, UglyToad.PdfPig.InternalParsingOptions parsingOptions = {UglyToad.PdfPig.InternalParsingOptions}) Line 66
	at C:\Users\bw\ws\projects\nm\sfc\Extern\PdfPig\src\UglyToad.PdfPig\Parser\PageFactory.cs(66)
UglyToad.PdfPig.dll!UglyToad.PdfPig.Content.Pages.GetPage(int pageNumber = 79, UglyToad.PdfPig.InternalParsingOptions parsingOptions = {UglyToad.PdfPig.InternalParsingOptions}) Line 68
	at C:\Users\bw\ws\projects\nm\sfc\Extern\PdfPig\src\UglyToad.PdfPig\Content\Pages.cs(68)
UglyToad.PdfPig.dll!UglyToad.PdfPig.PdfDocument.GetPage(int pageNumber = 79) Line 151
	at C:\Users\bw\ws\projects\nm\sfc\Extern\PdfPig\src\UglyToad.PdfPig\PdfDocument.cs(151)
GwkWinShared.dll!De.GwkIt.Core.Windows.Pdf.PdfDocument.PdfDocument(string pdf_full_file_name = "Q:\\Projekte\\SFCLCO\\Control\\01 CMM\\01 PROD\\22111201 PubIndex\\02 CMM SOURCE XML+PDF\\45153 CMM 21-01-01 Rev 0.pdf") Line 24
	at C:\Users\bw\ws\projects\shared\GwkWinShared\Pdf\PdfDocument.cs(24)
SfcBl.dll!sfc.businesslogic.Cmms.CmmContent.LoadPdf(sfc.businesslogic.Cmms.CmmImport import = {sfc.businesslogic.Cmms.CmmImport}, string pdf_file_name = "Q:\\Projekte\\SFCLCO\\Control\\01 CMM\\01 PROD\\22111201 PubIndex\\02 CMM SOURCE XML+PDF\\45153 CMM 21-01-01 Rev 0.pdf", string xml_out_dir = "Q:\\Projekte\\SFCLCO\\Control\\01 CMM\\01 PROD\\22111201 PubIndex\\11 CMM ANLYSE XML", bool write_xml = true) Line 51
	at C:\Users\bw\ws\projects\nm\sfc\Lib\SfcBl\Cmms\CmmContent.cs(51)
SfcBl.dll!sfc.businesslogic.Cmms.CmmContentDictionary.AddFromPdfFiles(System.Collections.Generic.IEnumerable<string> full_pdf_names = {string[364]}, string xml_out_dir = "Q:\\Projekte\\SFCLCO\\Control\\01 CMM\\01 PROD\\22111201 PubIndex\\11 CMM ANLYSE XML", bool allow_overwrite = false, bool do_write_xml = true) Line 44
	at C:\Users\bw\ws\projects\nm\sfc\Lib\SfcBl\Cmms\CmmContentDictionary.cs(44)
SfcBl.dll!sfc.businesslogic.Cmms.CmmContentDictionary.AddFromPdfDirectory(string pdf_in_dir = "Q:\\Projekte\\SFCLCO\\Control\\01 CMM\\01 PROD\\22111201 PubIndex\\02 CMM SOURCE XML+PDF", string xml_out_dir = "Q:\\Projekte\\SFCLCO\\Control\\01 CMM\\01 PROD\\22111201 PubIndex\\11 CMM ANLYSE XML", string mask = "*.pdf", bool allow_overwrite = false, bool do_write_xml = true) Line 21
	at C:\Users\bw\ws\projects\nm\sfc\Lib\SfcBl\Cmms\CmmContentDictionary.cs(21)
SfcBl.dll!sfc.businesslogic.Cmms.CmmImport.Cmms.get() Line 143
	at C:\Users\bw\ws\projects\nm\sfc\Lib\SfcBl\Cmms\CmmImport.cs(143)
SfcBl.dll!sfc.businesslogic.Cmms.CmmImport.CrossRef() Line 237
	at C:\Users\bw\ws\projects\nm\sfc\Lib\SfcBl\Cmms\CmmImport.cs(237)
SfcBl.dll!sfc.businesslogic.Cmms.CmmImport.ImportCmms(bool interactive = false) Line 185
	at C:\Users\bw\ws\projects\nm\sfc\Lib\SfcBl\Cmms\CmmImport.cs(185)
SfcBl.dll!sfc.businesslogic.Cmms.CmmImport.ImportCmms(string cmm_base_path = "Q:\\Projekte\\SFCLCO\\Control\\01 CMM\\01 PROD\\22111201 PubIndex", string global_main_path = "Q:\\Projekte\\SFCLCO\\Control\\01 CMM\\01 PROD", sfc.businesslogic.Cmms.ICmmResolver resolver = {sfc.businesslogic.Cmms.SfcCmmResolver}, bool interactive = false) Line 174
	at C:\Users\bw\ws\projects\nm\sfc\Lib\SfcBl\Cmms\CmmImport.cs(174)
SfcMain.dll!sfc.main.SfcApplicationStart.SfcApplicationStartBw() Line 109
	at C:\Users\bw\ws\projects\nm\sfc\Sfc\SfcMain\SfcApplicationStartBw.cs(109)
SfcMain.dll!sfc.main.SfcApplicationStart.Main() Line 56
	at C:\Users\bw\ws\projects\nm\sfc\Sfc\SfcMain\SfcApplicationStart.cs(56)
```

**Comment by fnatzke** [comment] 2022-12-20 04:28
@bweberde are you able to upload the PDF (as a file)?

**Comment by fnatzke** [comment] 2023-01-09 08:06
@bweberde ,

Seems to be caused by the "<<"" appearing after "CIDSystemInfo" on this line:

CIDSystemInfo <<

but no (dictionary) closing ">>" after the following line:

/Registry (F2+0) /Ordering (F2) /Supplement 0

Merging these two lines to one with fixes would make:

/CIDSystemInfo <</Registry (F2+0) /Ordering (F2) /Supplement 0 >> def


Replacement text in full:

`
 
/CIDInit /ProcSet findresource
begin 12 dict
begin begincmap
/CIDSystemInfo << /Registry (F2+0) /Ordering (F2) /Supplement 0 >> def
/CMapName /F2+0 def
/CMapType 2 def
1 begincodespacerange <020D> <020D> endcodespacerange
1 beginbfchar
<020D> <03A9>
endcmap CMapName currentdict /CMap defineresource pop end end
endbfcha


`

With these text changes the library parses without exception.

@EliotJones 

Unless this is found to be common I would suggest closing this issue for now without changing the library.

**Comment by EliotJones** [comment] 2023-05-21 13:59
I have pushed a change that should handle recovering the parser in cases where the dictionary is known to have a pre-determined number of required keys

**Closed by EliotJones** 2023-05-21 13:59 UTC
Labels: bug, testing, document-reading
