### ISSUE TITLE
PdfDocument.Open throws "Input string was not in a correct format"

### ISSUE THREAD

**Issue by Karamethien** [UglyToad/PdfPig#85] opened 2019-11-21 20:30 UTC
I am pretty new to programming.  

I added this nuget package to my project and copy the sample code.  I changed the file name and tried to run it and got "System.FormatException: 'Input string was not in a correct format.'" 

using (PdfDocument document = PdfDocument.Open(@"D:\Downloads\Document.pdf"))

Anyone know what may be causing it?   I am using PdfPig v0.0.9 and project is targeting .Net Framework 4.7.2

**Comment by EliotJones** [comment] 2019-11-22 07:17
Hi Karamethien, sorry to hear you're running in to this issue.

Would you be able to share the file located at `D:\Downloads\Document.pdf` please?

From your code sample it doesn't look like you're doing anything wrong so it might be a bug with the library on that file.

**Comment by EliotJones** [comment] 2020-06-20 12:42
I'm going to close this since hopefully the issue is resolved in newer versions. If it's still a problem feel free to reopen with some additional details.

**Closed by EliotJones** 2020-06-20 12:42 UTC
Labels: question
